language: node_js
node_js:
  - "6"
  - "8"

sudo: required

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  global:
    - COVERAGE=true
  matrix:
    # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=fastboot-addon-tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=fastboot-addon-tests

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: 05fd1578b53db2450402144ecf20105dc5ca6a99f44b41ebd6810bfadb4116c0
after_script:
  - codeclimate-test-reporter < lcov.dat
  - codecov
